fix: Prevent starting up if window is not defined (#248)
Guard @sentry/replay setup if `window` is not defined.

**Test Notes:**

I setup replays on my gatsby test app and was able to recreate the issue:

The config:
```typescript
#gatsby-config.ts

const config: GatsbyConfig = {
  ...
  plugins: [
    {
      resolve: "@sentry/gatsby",
    },
  ],
};
export default config;
```

```typescript
#sentry.config.ts

import * as Sentry from '@sentry/gatsby';
import { Replay } from "@sentry/replay";

Sentry.init({
  dsn: "https://c214503190724086b0b4017d8fe5d65a@o1176005.ingest.sentry.io/6622945",
  sampleRate: 1.0, // Adjust this value in production
  integrations: [
    new Replay(),
  ],
});
```

The failing output:
```bash
There was an error compiling the html.js component for the development server.
See our docs page on debugging HTML builds for help https://gatsby.dev/debug-html ReferenceError: window is not defined


  1226 |         var _this = this;
  1227 |         // XXX: See method comments above
> 1228 |         window.setTimeout(function () { return _this.start(); });
       |         ^
  1229 |     };
  1230 |     /**
  1231 |      * Initializes the plugin.


  WebpackError: ReferenceError: window is not defined
```

After the fix we're able to build and run the app, and record replays!

| Test App | Replay |
| --- | --- |
| <img width="1156" alt="Screen Shot 2022-10-18 at 5 38 11 PM"
src="https://user-images.githubusercontent.com/187460/196570601-daf68ea5-25e4-4804-9365-9dab03ddf3a1.png">
| <img width="438" alt="Screen Shot 2022-10-18 at 5 37 09 PM"
src="https://user-images.githubusercontent.com/187460/196570323-85e7d204-b445-4457-aa2b-8af8ea613688.png">
|

In a gatsby app, or most of these other frameworks, it is possible to have a node-only or browser-only config. With atsby, for example, as a work around I would remove `new Replay()` from `sentry.config.ts` and instead create `gatsby-browser.tsx` with the following content which will to manually start the replay session:

```typescript
# gatsby-browser.tsx
const { Replay } = require("@sentry/replay");

exports.wrapRootElement = ({ element, props }) => {
  const replay = new Replay({
    blockAllMedia: false,
    maskAllText: false,
  });
  replay.start();

  return element;
};
```

Fixes #246